RECURSO_TIPO_COMERCIO = "comercio"
RECURSO_TIPO_PUBLICACION = "publicacion"
RECURSO_TIPO_HISTORIA = "historia"

RECURSOS_DENUNCIABLES = {
    RECURSO_TIPO_COMERCIO,
    RECURSO_TIPO_PUBLICACION,
    RECURSO_TIPO_HISTORIA,
}

MOTIVO_CONTENIDO_INAPROPIADO = "contenido_inapropiado"
MOTIVO_FRAUDE_ENGANO = "fraude_engano"
MOTIVO_SUPLANTACION = "suplantacion"
MOTIVO_DATOS_PERSONALES = "datos_personales"
MOTIVO_PROPIEDAD_INTELECTUAL = "propiedad_intelectual"
MOTIVO_PRODUCTO_SERVICIO_RESTRINGIDO = "producto_servicio_restringido"
MOTIVO_SPAM = "spam"
MOTIVO_OTRO = "otro"

MOTIVOS_DENUNCIA = {
    MOTIVO_CONTENIDO_INAPROPIADO,
    MOTIVO_FRAUDE_ENGANO,
    MOTIVO_SUPLANTACION,
    MOTIVO_DATOS_PERSONALES,
    MOTIVO_PROPIEDAD_INTELECTUAL,
    MOTIVO_PRODUCTO_SERVICIO_RESTRINGIDO,
    MOTIVO_SPAM,
    MOTIVO_OTRO,
}

ESTADO_DENUNCIA_RECIBIDA = "recibida"
ESTADO_DENUNCIA_RESUELTA = "resuelta"
ESTADOS_DENUNCIA = {ESTADO_DENUNCIA_RECIBIDA, ESTADO_DENUNCIA_RESUELTA}

ACCION_RESOLVER_SIN_ACCION = "resolver_sin_accion"
ACCION_OCULTAR_RECURSO = "ocultar_recurso"
ACCION_RESTAURAR_RECURSO = "restaurar_recurso"
ACCIONES_MODERACION = {
    ACCION_RESOLVER_SIN_ACCION,
    ACCION_OCULTAR_RECURSO,
    ACCION_RESTAURAR_RECURSO,
}

RESULTADO_APLICADO = "aplicado"
RESULTADO_SIN_CAMBIO = "sin_cambio"

MOTIVOS_DECISION_MODERACION = {
    "sin_incumplimiento",
    "incumplimiento_confirmado",
    "contenido_no_disponible",
    "correccion_operativa",
    "otro",
}
