RECURSO_TIPO_COMERCIO = "comercio"
RECURSO_TIPO_PUBLICACION = "publicacion"
RECURSO_TIPO_HISTORIA = "historia"

RECURSOS_DENUNCIABLES = {
    RECURSO_TIPO_COMERCIO,
    RECURSO_TIPO_PUBLICACION,
    RECURSO_TIPO_HISTORIA,
}

MOTIVO_CONTENIDO_INAPROPIADO = "contenido_inapropiado"
MOTIVO_FRAUDE_ENGANO = "fraude_engano"
MOTIVO_SUPLANTACION = "suplantacion"
MOTIVO_DATOS_PERSONALES = "datos_personales"
MOTIVO_PROPIEDAD_INTELECTUAL = "propiedad_intelectual"
MOTIVO_PRODUCTO_SERVICIO_RESTRINGIDO = "producto_servicio_restringido"
MOTIVO_SPAM = "spam"
MOTIVO_OTRO = "otro"

MOTIVOS_DENUNCIA = {
    MOTIVO_CONTENIDO_INAPROPIADO,
    MOTIVO_FRAUDE_ENGANO,
    MOTIVO_SUPLANTACION,
    MOTIVO_DATOS_PERSONALES,
    MOTIVO_PROPIEDAD_INTELECTUAL,
    MOTIVO_PRODUCTO_SERVICIO_RESTRINGIDO,
    MOTIVO_SPAM,
    MOTIVO_OTRO,
}

ESTADO_DENUNCIA_RECIBIDA = "recibida"
